# Generated by Django 2.0.7 on 2018-07-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='login',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
